name: XLR8TD
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - aom=3.5.0
  - attr=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=3.0.0
  - dbus=1.13.18
  - dlib=19.24.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - jack=1.9.22
  - jasper=2.0.33
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcups=2.3.3
  - libcurand=10.3.3.141
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.0
  - libglu=9.0.0
  - libgpg-error=1.47
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.1
  - nspr=4.35
  - nss=3.94
  - numpy=1.26.0
  - numpy-base=1.26.0
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.4.0
  - openssl=3.1.3
  - p11-kit=0.24.1
  - packaging=23.2
  - pcre=8.45
  - pcre2=10.40
  - pillow=10.0.1
  - pip=23.2.1
  - pixman=0.42.2
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - py-opencv=4.7.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.31.0
  - scipy=1.11.3
  - setuptools=68.0.0
  - sip=6.7.11
  - six=1.16.0
  - sqlite=3.41.2
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tornado=6.3.2
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - customtkinter==5.2.0
      - darkdetect==0.8.0
      - docutils==0.20.1
      - fsspec==2023.10.0
      - huggingface-hub==0.18.0
      - kivy==2.2.1
      - kivy-examples==2.2.1
      - kivy-garden==0.1.5
      - kivymd==1.1.1
      - pygments==2.16.1
      - python-io==0.3
      - safetensors==0.4.0
      - timm==0.9.8
      - tqdm==4.66.1
